from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator
from schemas.chat_file import ChatAttachmentRef


class AIChatCommand(BaseModel):
    type: Literal["prompt", "continue", "retry", "query"] = Field(
        description=(
            "Streaming conversation command type. prompt starts new input, retry resumes and retries "
            "the last failed interrupt, and query submits a choice from a query-tool interrupt."
        ),
        examples=["query"],
    )
    prompt: str | None = Field(
        default=None,
        description="Text attached to the command. The top-level prompt is used when prompt is omitted; retry and query may omit it.",
        examples=["Continue processing the resume."],
    )
    choice: Literal["firstChoice", "secondChoice", "thirdChoice", "other"] | None = Field(
        default=None,
        description="User choice submitted by a query command. Required only when command.type is query.",
        examples=["firstChoice"],
    )
    note: str | None = Field(
        default=None,
        description="Additional note submitted by a query command; it may be attached to any user choice.",
        examples=["I prefer the lowest-cost option first."],
    )


class AIChatRequest(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "selection_id": 1,
                    "prompt": "请帮我总结这份简历的优势。",
                    "thread_id": "conversation-001",
                    "file_ids": ["A1B2C3"],
                }
            ]
        }
    )

    selection_id: int = Field(
        description="Model selection record ID corresponding to tb_model_selection.id.",
        examples=[1],
    )
    prompt: str | None = Field(
        default=None,
        description="User text message. Optional when attachments are present and required for text-only requests.",
        examples=["Summarize the strengths of this resume."],
    )
    thread_id: str | None = Field(
        default=None,
        description="Conversation thread ID. Reuses a conversation when provided; generated by the server when omitted.",
        examples=["conversation-001"],
    )
    file_ids: list[str] = Field(
        default_factory=list,
        description="List of historical file IDs to reuse in the current request.",
        examples=[["A1B2C3"]],
    )


class AIChatResponse(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "thread_id": "conversation-001",
                    "content": "这份简历的主要优势是项目经历完整、技术栈清晰。",
                },
                {
                    "thread_id": "conversation-002",
                    "content": [
                        {
                            "type": "text",
                            "text": "你好！有什么我可以帮您的吗？",
                            "index": 0,
                            "extras": {},
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": "data:image/png;base64,iVBORw0KGgo="
                            },
                            "index": 1,
                            "extras": {},
                        },
                    ],
                }
            ]
        }
    )

    thread_id: str = Field(
        description="Conversation thread ID used for this request.",
        examples=["conversation-001"],
    )
    content: Any = Field(
        description="Final AI response. Strings are returned as-is; structured text and image content blocks retain their JSON shape.",
        examples=[
            "这份简历的主要优势是项目经历完整、技术栈清晰。",
            [
                {
                    "type": "text",
                    "text": "你好！有什么我可以帮您的吗？",
                    "index": 0,
                    "extras": {},
                }
            ],
        ],
    )


class AIChatHistoryMessage(BaseModel):
    role: str = Field(
        description="Message role. human maps to user, ai maps to assistant, and tool remains tool.",
        examples=["assistant"],
    )
    type: str = Field(
        description="LangChain message type.",
        examples=["ai"],
    )
    content: Any = Field(
        description="Message content. User messages expose display_content visible to the user; hidden attachment bodies are not sent to the frontend.",
        examples=["这份简历的主要优势是项目经历完整、技术栈清晰。"],
    )
    attachments: list[ChatAttachmentRef] | None = Field(
        default=None,
        description="Attachments associated with a user message. Returned only for messages with attachments.",
    )
    reasoning: str | None = Field(
        default=None,
        description="Intermediate reasoning before model inference or tool calls; the frontend should render it collapsed.",
        examples=["我需要先检索最新资料。"],
    )
    reasoning_duration_ms: int | None = Field(
        default=None,
        description="Time spent generating reasoning, in milliseconds. Returned only when reasoning exists.",
        examples=[12000],
    )
    name: str | None = Field(
        default=None,
        description="Message name, usually used for tool messages or named model messages.",
        examples=["web_search_exa"],
    )
    tool_call_id: str | None = Field(
        default=None,
        description="Tool-call ID, returned only for tool messages.",
        examples=["call-001"],
    )
    status: str | None = Field(
        default=None,
        description="Tool-message status, such as success or error.",
        examples=["success"],
    )


class AIChatHistorySummary(BaseModel):
    thread_id: str = Field(
        description="Conversation thread ID.",
        examples=["conversation-001"],
    )
    title: str = Field(
        description="Conversation title, using a truncated first user message by default.",
        examples=["请帮我总结这份简历的优势。"],
    )
    last_message_preview: str = Field(
        description="Preview of the last message.",
        examples=["这份简历的主要优势是项目经历完整、技术栈清晰。"],
    )
    message_count: int = Field(
        description="Number of messages in the latest checkpoint.",
        examples=[2],
    )
    attachment_count: int = Field(
        default=0,
        description="Number of unique attachments associated with the current thread.",
        examples=[1],
    )
    requires_image_input: bool = Field(
        default=False,
        description="Whether the current thread contains image-mode attachments, so the frontend can warn that a text-only model may not use the original images.",
        examples=[True],
    )
    context_compacted: bool = Field(
        default=False,
        description="Whether Supervisor has successfully created a reusable auto-compacted context view for this thread.",
        examples=[True],
    )
    updated_at: datetime = Field(
        description="Creation time of the latest conversation checkpoint.",
        examples=["2026-04-25T20:00:00"],
    )


class AIChatHistoryListResponse(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "items": [
                        {
                            "thread_id": "conversation-001",
                            "title": "请帮我总结这份简历的优势。",
                            "last_message_preview": "这份简历的主要优势是项目经历完整、技术栈清晰。",
                            "message_count": 2,
                            "attachment_count": 1,
                            "requires_image_input": True,
                            "context_compacted": True,
                            "updated_at": "2026-04-25T20:00:00",
                        }
                    ],
                    "limit": 20,
                    "offset": 0,
                }
            ]
        }
    )

    items: list[AIChatHistorySummary] = Field(
        description="Conversation-history summaries ordered by most recent update.",
    )
    limit: int = Field(
        description="Page size for this query.",
        examples=[20],
    )
    offset: int = Field(
        description="Page offset for this query.",
        examples=[0],
    )


class AIChatHistoryDetailResponse(AIChatHistorySummary):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "thread_id": "conversation-001",
                    "title": "请帮我总结这份简历的优势。",
                    "last_message_preview": "这份简历的主要优势是项目经历完整、技术栈清晰。",
                    "message_count": 2,
                    "attachment_count": 1,
                    "requires_image_input": False,
                    "context_compacted": True,
                    "updated_at": "2026-04-25T20:00:00",
                    "messages": [
                        {
                            "role": "user",
                            "type": "human",
                            "content": "请帮我总结这份简历的优势。",
                            "attachments": [
                                {
                                    "file_id": "A1B2C3",
                                    "original_filename": "resume.pdf",
                                    "media_type": "application/pdf",
                                    "injection_mode": "image",
                                }
                            ],
                        },
                        {
                            "role": "assistant",
                            "type": "ai",
                            "content": "这份简历的主要优势是项目经历完整、技术栈清晰。",
                        },
                    ],
                }
            ]
        }
    )

    messages: list[AIChatHistoryMessage] = Field(
        description="Complete message list saved in the latest checkpoint for the current conversation.",
    )


class AIChatStreamRequest(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "selection_id": 1,
                    "prompt": "请帮我总结这份简历的优势。",
                    "thread_id": "conversation-001",
                    "file_ids": ["A1B2C3"],
                },
                {
                    "selection_id": 1,
                    "thread_id": "conversation-001",
                    "command": {"type": "retry"},
                },
                {
                    "selection_id": 1,
                    "thread_id": "conversation-001",
                    "command": {
                        "type": "query",
                        "choice": "firstChoice",
                        "note": "按推荐方案继续。",
                    },
                },
            ]
        }
    )

    selection_id: int = Field(
        description="Model selection record ID corresponding to tb_model_selection.id.",
        examples=[1],
    )
    prompt: str | None = Field(
        default=None,
        description="User text message. Optional when attachments are present or when using a retry command.",
        examples=["Summarize the strengths of this resume."],
    )
    thread_id: str | None = Field(
        default=None,
        description="Conversation thread ID. retry and query commands must reuse the thread ID returned by the previous interrupt.",
        examples=["conversation-001"],
    )
    file_ids: list[str] = Field(
        default_factory=list,
        description="List of historical file IDs to reuse in the current request.",
        examples=[["A1B2C3"]],
    )
    command: AIChatCommand | None = Field(
        default=None,
        description="Streaming conversation command. When omitted, the request is treated as prompt; retry resumes a failed interrupt and query resumes a user-choice interrupt.",
        examples=[
            {
                "type": "query",
                "choice": "firstChoice",
                "note": "Continue with the recommended option.",
            }
        ],
    )

    @model_validator(mode="after")
    def validate_stream_command(self) -> "AIChatStreamRequest":
        command_type = self.command.type if self.command else "prompt"

        if command_type in {"retry", "query"}:
            if not self.thread_id:
                raise ValueError(f"thread_id is required when command.type is {command_type}")
            if command_type == "query" and self.command and self.command.choice is None:
                raise ValueError("choice is required when command.type is query")
            return self

        return self
